import { CardDef, CardId } from './types';

export const CARD_DEFINITIONS: Record<CardId, CardDef> = {
  knight: {
    id: 'knight',
    name: 'Knight',
    nameTr: 'Şövalye',
    elixir: 3,
    type: 'troop',
    description: 'Dayanıklı ve güvenilir yakın dövüş kılıç ustası.',
    icon: '⚔️',
    color: '#3B82F6',
    count: 1,
    hp: 1400,
    damage: 160,
    speed: 1.2,
    range: 28,
    attackSpeed: 1.2,
    targets: 'ground',
  },
  archers: {
    id: 'archers',
    name: 'Archers',
    nameTr: 'Okçular',
    elixir: 3,
    type: 'troop',
    description: 'Uzak mesafeden hem hava hem kara hedeflerini vuran ikili okçular.',
    icon: '🏹',
    color: '#EC4899',
    count: 2,
    hp: 420,
    damage: 85,
    speed: 1.3,
    range: 150,
    attackSpeed: 1.0,
    targets: 'all',
  },
  giant: {
    id: 'giant',
    name: 'Giant',
    nameTr: 'Dev',
    elixir: 5,
    type: 'troop',
    description: 'Yalnızca kuleleri hedefleyen devasa zırhlı kuşatma tankı.',
    icon: '🗿',
    color: '#F97316',
    count: 1,
    hp: 3300,
    damage: 220,
    speed: 0.8,
    range: 35,
    attackSpeed: 1.5,
    targets: 'buildings',
  },
  skeleton_army: {
    id: 'skeleton_army',
    name: 'Skeleton Army',
    nameTr: 'İskelet Ordusu',
    elixir: 3,
    type: 'troop',
    description: 'Büyük düşmanları hızla alt eden 6 çevik küçük iskelet.',
    icon: '💀',
    color: '#94A3B8',
    count: 6,
    hp: 95,
    damage: 75,
    speed: 1.8,
    range: 24,
    attackSpeed: 0.9,
    targets: 'ground',
  },
  wizard: {
    id: 'wizard',
    name: 'Wizard',
    nameTr: 'Büyücü',
    elixir: 5,
    type: 'troop',
    description: 'Düşman gruplarını kül eden alan etkili ateş patlamaları savurur.',
    icon: '🧙‍♂️',
    color: '#8B5CF6',
    count: 1,
    hp: 620,
    damage: 155,
    speed: 1.25,
    range: 140,
    attackSpeed: 1.4,
    targets: 'all',
    isSplash: true,
    splashRadius: 50,
  },
  fireball: {
    id: 'fireball',
    name: 'Fireball',
    nameTr: 'Ateş Topu',
    elixir: 4,
    type: 'spell',
    description: 'Arenanın herhangi bir noktasına atılabilen yüksek hasarlı alev büyüsü.',
    icon: '🔥',
    color: '#EF4444',
    count: 1,
    hp: 0,
    damage: 580,
    speed: 0,
    range: 0,
    attackSpeed: 0,
    targets: 'all',
    isSplash: true,
    splashRadius: 75,
  },
  goblin_gang: {
    id: 'goblin_gang',
    name: 'Goblin Gang',
    nameTr: 'Goblin Çetesi',
    elixir: 3,
    type: 'troop',
    description: 'Arenaya hızla hücum eden 4 vahşi ve hızlı goblin birliği.',
    icon: '🗡️',
    color: '#10B981',
    count: 4,
    hp: 220,
    damage: 95,
    speed: 2.0,
    range: 30,
    attackSpeed: 0.9,
    targets: 'ground',
  },
  baby_dragon: {
    id: 'baby_dragon',
    name: 'Baby Dragon',
    nameTr: 'Bebek Ejderha',
    elixir: 4,
    type: 'troop',
    description: 'Nehirlerin üstünden uçan ve havadan alev püskürten sevimli ejderha.',
    icon: '🐲',
    color: '#14B8A6',
    count: 1,
    hp: 1150,
    damage: 135,
    speed: 1.5,
    range: 125,
    attackSpeed: 1.3,
    targets: 'all',
    isFlying: true,
    isSplash: true,
    splashRadius: 40,
  },
};

export const ALL_CARD_IDS: CardId[] = [
  'knight',
  'archers',
  'giant',
  'skeleton_army',
  'wizard',
  'fireball',
  'goblin_gang',
  'baby_dragon',
];
